# Configuration fragment for assortment drawer ports in the Concertina.
#
# This fragment adds a set of three large cuboid holes in the front of the
# central housing. They’re about the right size for drawers to hold stationery.
# The drawers themselves are not modeled by the DMOTE application.

custom-bodies:
  # As a piece of design for manufacturing, both to support printers with a
  # z-axis limitation lower than the full central housing and to limit the need
  # for supports, print the outermost parts of the central housing separately.
  left-hand-bookend:
    include: true
    parent-body: central-housing
    cut:
      shape:
        - [assortment1, E,
           {anchoring: {intrinsic-offset: [100, 0, 0]},
            size: [200, 200, 200]}]
  right-hand-bookend:
    include: true
    parent-body: central-housing
    cut:
      shape:
        - [assortment1, W,
           {anchoring: {intrinsic-offset: [-100, 0, 0]},
            size: [200, 200, 200]}]
flanges:
  assortment-bookend-flanges:
    include: true
    bolts:
      include: true
      bolt-properties:
        m-diameter: 3
        head-type: countersunk
        point-type: cone
        include-threading: true
        total-length: 12
        channel-length: 4
    positions:
    # Mounting screws in the loft of the central housing:
    - anchoring:
        anchor: assortment1
        side: NW
        segment: 0
        intrinsic-rotation: [0, π/-2, 0]
        intrinsic-offset: [-2, -12, 6]
    - anchoring:
        anchor: assortment1
        side: SW
        segment: 0
        intrinsic-rotation: [0, π/-2, 0]
        intrinsic-offset: [-2, 10, 6]
    - anchoring:
        anchor: assortment1
        side: NE
        segment: 0
        intrinsic-rotation: [0, π/2, 0]
        intrinsic-offset: [2, -12, 6]
    - anchoring:
        anchor: assortment1
        side: SE
        segment: 0
        intrinsic-rotation: [0, π/2, 0]
        intrinsic-offset: [2, 10, 6]
    # One screw beneath each of the four lower corners of each assortment port,
    # right-hand-side.
    - anchoring:
        anchor: assortment1
        side: SW
        segment: 2
        intrinsic-rotation: [0, π/-2, 0]
        intrinsic-offset: [-2, 12, -2]
    - anchoring:
        anchor: assortment1
        side: NW
        segment: 2
        intrinsic-rotation: [0, π/-2, 0]
        intrinsic-offset: [-2, -6, -2]
    - anchoring:
        anchor: assortment2
        side: SW
        segment: 2
        intrinsic-rotation: [0, π/-2, 0]
        intrinsic-offset: [-2, 12, -2]
    - anchoring:
        anchor: assortment2
        side: NW
        segment: 2
        intrinsic-rotation: [0, π/-2, 0]
        intrinsic-offset: [-2, -6, -2]
    - anchoring:
        anchor: assortment3
        side: SW
        segment: 2
        intrinsic-rotation: [0, π/-2, 0]
        intrinsic-offset: [-2, 12, -2]
    - anchoring:
        anchor: assortment3
        side: NW
        segment: 2
        intrinsic-rotation: [0, π/-2, 0]
        intrinsic-offset: [-2, -6, -2]
    # The same on the left.
    - anchoring:
        anchor: assortment1
        side: SE
        segment: 2
        intrinsic-rotation: [0, π/2, 0]
        intrinsic-offset: [2, 12, -2]
    - anchoring:
        anchor: assortment1
        side: NE
        segment: 2
        intrinsic-rotation: [0, π/2, 0]
        intrinsic-offset: [2, -6, -2]
    - anchoring:
        anchor: assortment2
        side: SE
        segment: 2
        intrinsic-rotation: [0, π/2, 0]
        intrinsic-offset: [2, 12, -2]
    - anchoring:
        anchor: assortment2
        side: NE
        segment: 2
        intrinsic-rotation: [0, π/2, 0]
        intrinsic-offset: [2, -6, -2]
    - anchoring:
        anchor: assortment3
        side: SE
        segment: 2
        intrinsic-rotation: [0, π/2, 0]
        intrinsic-offset: [2, 12, -2]
    - anchoring:
        anchor: assortment3
        side: NE
        segment: 2
        intrinsic-rotation: [0, π/2, 0]
        intrinsic-offset: [2, -6, -2]
  central-housing-bottom-plate:
    include: true
    positions:
    # The first of these go inside the centermost piece of the
    # housing.
    - boss-alias: bottom-central-N
      # Not reflected; it would just end up in the same position.
      anchoring:
        intrinsic-offset: [0, 36, 0]
    - boss-alias: bottom-central-NE
      reflect: true  # Copy to the NW side.
      anchoring:
        intrinsic-offset: [72, 36, 0]
    - boss-alias: bottom-central-SE
      reflect: true
      anchoring:
        intrinsic-offset: [72, -51, 0]
    - boss-alias: bottom-central-S
      anchoring:
        intrinsic-offset: [0, -51, 0]
    # The remaining positions are inside the custom bodies made
    # from the central housing.
    - boss-alias: bottom-bookend-N
      reflect: true
      anchoring:
        anchor: ci-far-base
        intrinsic-offset: [-7, -4, 0]
    - boss-alias: bottom-bookend-S
      reflect: true
      anchoring:
        anchor: ci-near-base
        intrinsic-offset: [-10, 4, 0]
    - boss-alias: bottom-bookend-W
      reflect: true
      anchoring:
        intrinsic-offset: [87, -7.5, 0]
ports:
  # Three slots follow for assortment drawers, with 4 mm between each.
  # There is also a 4 mm lip above the top drawer, partly for aesthetics and
  # partly because this is the natural place to grab and lift the keyboard.
  assortment1:
    include: true
    size: [162, 92, 25]
    anchoring:
      intrinsic-rotation: [0, 0, π]
      intrinsic-offset: [0, -55, 106]
    holder:
      include: true
      alias: assortment1-holder
      thickness: 2
  assortment2:
    include: true
    size: [162, 92, 25]
    anchoring:
      intrinsic-rotation: [0, 0, π]
      intrinsic-offset: [0, -55, 77]
    holder:
      include: true
      alias: assortment2-holder
      thickness: 2
  assortment3:
    include: true
    size: [162, 92, 25]
    anchoring:
      intrinsic-rotation: [0, 0, π]
      intrinsic-offset: [0, -55, 48]
    holder:
      include: true
      alias: assortment3-holder
      thickness: 2
tweaks:
  # Walls to ground on both flanks of the assortment ports.
  # These provide an additional lower compartment that is not a port but can be
  # filled with non-printed material to add mass to the keyboard.
  central-dividers:
  - to-ground: true
    chunk-size: 2
    hull-around:
    - hull-around:
      - [assortment1, NE, {anchoring: {intrinsic-offset: [0.5, -1, 0]}, size: 1}]
      - [assortment1, SE, {anchoring: {intrinsic-offset: [0.5, 0, 0]}, size: 1}]
    - hull-around:
      - [assortment3, NE, 2, {anchoring: {intrinsic-offset: [0.5, -1, -12]}, size: 1}]
      - [assortment3, SE, 2, {anchoring: {intrinsic-offset: [0.5, 0, -12]}, size: 1}]
    - hull-around:
      - [assortment3, NE, 2, {anchoring: {intrinsic-offset: [4.5, -1, -16]}, size: 1}]
      - [assortment3, SE, 2, {anchoring: {intrinsic-offset: [4.5, 0, -16]}, size: 1}]
  - to-ground: true
    chunk-size: 2
    hull-around:
    - hull-around:
      - [assortment1, NW, {anchoring: {intrinsic-offset: [-0.5, -1, 0]}, size: 1}]
      - [assortment1, SW, {anchoring: {intrinsic-offset: [-0.5, 0, 0]}, size: 1}]
    - hull-around:
      - [assortment3, NW, 2, {anchoring: {intrinsic-offset: [-0.5, -1, -12]}, size: 1}]
      - [assortment3, SW, 2, {anchoring: {intrinsic-offset: [-0.5, 0, -12]}, size: 1}]
    - hull-around:
      - [assortment3, NW, 2, {anchoring: {intrinsic-offset: [-4.5, -1, -16]}, size: 1}]
      - [assortment3, SW, 2, {anchoring: {intrinsic-offset: [-4.5, 0, -16]}, size: 1}]
  # Irregular tetrahedrons going into the loft of the central housing.
  # Their shape is meant to ease cable runs and printing, while accommodating
  # long flange screws.
  central-flanges:
  - above-ground: true
    hull-around:
    - [assortment1, NW, 0, {anchoring: {intrinsic-offset: [0, -2, 0]}, size: 4}]
    - [assortment1, NW, 0, {anchoring: {intrinsic-offset: [0, -15, 9]}, size: [4, 1, 18]}]
    - [assortment1, NW, 0, {anchoring: {intrinsic-offset: [75, -0.5, 2]}, size: [1, 1, 4]}]
  - above-ground: true
    hull-around:
    - [assortment1, NE, 0, {anchoring: {intrinsic-offset: [0, -2, 0]}, size: 4}]
    - [assortment1, NE, 0, {anchoring: {intrinsic-offset: [0, -15, 9]}, size: [4, 1, 18]}]
    - [assortment1, NE, 0, {anchoring: {intrinsic-offset: [-75, -0.5, 2]}, size: [1, 1, 4]}]
  - above-ground: true
    hull-around:
    - [assortment1, SW, 0, {anchoring: {intrinsic-offset: [0, 0, 0]}, size: 4}]
    - [assortment1, SW, 0, {anchoring: {intrinsic-offset: [0, 13, 9]}, size: [4, 1, 18]}]
    - [assortment1, SW, 0, {anchoring: {intrinsic-offset: [75, 0, 2]}, size: [1, 1, 4]}]
  - above-ground: true
    hull-around:
    - [assortment1, SE, 0, {anchoring: {intrinsic-offset: [0, 0, 0]}, size: 4}]
    - [assortment1, SE, 0, {anchoring: {intrinsic-offset: [0, 13, 9]}, size: [4, 1, 18]}]
    - [assortment1, SE, 0, {anchoring: {intrinsic-offset: [-75, 0, 2]}, size: [1, 1, 4]}]
  # Extra shapes beneath the lowest assortment port contain the last sets of
  # flange screws and magnets.
  outer-bosses-beneath-drawer-stack:
  - above-ground: true
    hull-around:
    - [assortment3, NW, 2, {anchoring: {intrinsic-offset: [6, -11, -2]}, size: [12, 22, 4]}]
    - [assortment3, NW, 2, {anchoring: {intrinsic-offset: [9, -11, -1]}, size: [18, 22, 2]}]
  - above-ground: true
    hull-around:
    - [assortment3, NE, 2, {anchoring: {intrinsic-offset: [-6, -11, -2]}, size: [12, 22, 4]}]
    - [assortment3, NE, 2, {anchoring: {intrinsic-offset: [-9, -11, -1]}, size: [18, 22, 2]}]
  inner-bosses-beneath-drawer-stack:
  - above-ground: true
    hull-around:
    - [assortment3, SW, 2, {anchoring: {intrinsic-offset: [6, 8, -2]}, size: [12, 18, 4]}]
    - [assortment3, SW, 2, {anchoring: {intrinsic-offset: [9, 8, -1]}, size: [18, 18, 2]}]
  - above-ground: true
    hull-around:
    - [assortment3, SE, 2, {anchoring: {intrinsic-offset: [-6, 8, -2]}, size: [12, 18, 4]}]
    - [assortment3, SE, 2, {anchoring: {intrinsic-offset: [-9, 8, -1]}, size: [18, 18, 2]}]
